# Generated by Django 5.0.1 on 2026-08-04 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("short_description", models.TextField(blank=True, default="")),
                ("cuisines", models.JSONField(blank=True, default=list)),
                ("price_range", models.CharField(blank=True, default="", max_length=4)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurants/logos/"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="restaurants/covers/"
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("use_different_whatsapp", models.BooleanField(default=False)),
                (
                    "secondary_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "street_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                ("city_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("rating_histogram", models.JSONField(blank=True, default=dict)),
                ("is_paused", models.BooleanField(default=False)),
                ("is_permanently_closed", models.BooleanField(default=False)),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("unclaimed", "Unclaimed"),
                            ("pending_claim", "Pending claim"),
                        ],
                        default="owned",
                        max_length=20,
                    ),
                ),
                ("setup_checklist", models.JSONField(blank=True, default=dict)),
                (
                    "promo_default_radius_km",
                    models.PositiveSmallIntegerField(default=5),
                ),
                (
                    "promo_default_duration_days",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("notify_on_promo_approval", models.BooleanField(default=True)),
                ("auto_request_promo_on_deal", models.BooleanField(default=False)),
                ("products_created_this_month", models.PositiveIntegerField(default=0)),
                ("products_quota_month", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
