# Generated by Django 5.0.1 on 2026-08-05 08:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("deal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "items_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "savings_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "savings_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("terms", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("hidden", "Hidden"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(blank=True, default="", max_length=32)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "subcategory",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "item_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Chicken", "Chicken"),
                            ("Beef", "Beef"),
                            ("Mutton", "Mutton"),
                            ("Fish", "Fish"),
                            ("Veg", "Veg"),
                            ("Vegetarian", "Vegetarian"),
                            ("Egg", "Egg"),
                            ("Mixed", "Mixed"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("sku", models.CharField(blank=True, default="", max_length=40)),
                ("is_available", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                (
                    "spicy_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "prep_time_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("emoji", models.CharField(blank=True, default="", max_length=16)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="restaurants.menucategory",
                    ),
                ),
                (
                    "cross_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cross_listed_items",
                        to="restaurants.menucategory",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_label", models.CharField(max_length=40)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="restaurants.deal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_lines",
                        to="restaurants.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="restaurants.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="menucategory",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "slug"), name="uniq_restaurant_category_slug"
            ),
        ),
    ]
