# Generated by Django 5.0.1 on 2026-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_global_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="is_promoted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deal",
            name="promoted_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="promoted_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_promoted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="promoted_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="promoted_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["is_promoted", "promoted_ends_at"], name="deal_promo_ends_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["is_promoted", "promoted_ends_at"],
                name="menuitem_promo_ends_idx",
            ),
        ),
    ]
