# Generated by Django 5.2.4 on 2026-08-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_city_fk'),
        ('restaurants', '0004_deal_is_promoted_deal_promoted_ends_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='geo.city'),
        ),
    ]
