# Generated by Django 5.2.4 on 2026-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_city_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
