# Generated by Django 5.0.1 on 2026-08-05 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0002_menu_deals_content_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("menu_item", "Menu item"), ("deal", "Deal")],
                        max_length=20,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, max_length=512, upload_to="mediahub/"),
                ),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("is_cover", models.BooleanField(default=False)),
                ("is_feed_video", models.BooleanField(default=True)),
                (
                    "processing_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "hls_master_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "hls_master_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                (
                    "thumbnail_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
                ("resolutions", models.JSONField(blank=True, default=list)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="restaurants.deal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_media",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "content media",
                "ordering": ["order_index", "created_at"],
            },
        ),
    ]
