# Generated by Django 5.0.1 on 2026-08-04 06:49

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                ("otp_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo_status_alerts", models.BooleanField(default=True)),
                ("new_follower_alerts", models.BooleanField(default=True)),
                ("weekly_performance_digest", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ur", "Urdu")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "signup_intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("restaurant", "Restaurant"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "active_mode",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("restaurant", "Restaurant"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "last_active_mode",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("restaurant", "Restaurant"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuisines", models.JSONField(blank=True, default=list)),
                ("price_ranges", models.JSONField(blank=True, default=list)),
                ("max_distance_km", models.PositiveSmallIntegerField(default=5)),
                ("city_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ur", "Urdu")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "customer_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to="accounts.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_reminders", models.BooleanField(default=True)),
                ("new_deals_from_saved", models.BooleanField(default=True)),
                ("nearby_flash_deals", models.BooleanField(default=False)),
                ("new_videos_from_followed", models.BooleanField(default=True)),
                ("weekly_digest", models.BooleanField(default=False)),
                ("security_alerts", models.BooleanField(default=True)),
                (
                    "customer_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_setting",
                        to="accounts.customerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("watch_history", models.JSONField(blank=True, default=list)),
                ("search_history", models.JSONField(blank=True, default=list)),
                ("pending_save", models.JSONField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merged_into_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_guest_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
