# Generated by Django 5.0.1 on 2026-08-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantnotificationsetting",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_setting",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurantpreference",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to="restaurants.restaurant",
            ),
        ),
    ]
