# Generated by Django 5.0.1 on 2026-08-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customernotificationsetting",
            name="enable_push_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsetting",
            name="enable_push_notification",
            field=models.BooleanField(default=True),
        ),
    ]
