# Generated by Django 5.2.4 on 2026-08-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_enable_push_notification'),
        ('geo', '0001_city_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpreference',
            name='city_id',
        ),
        migrations.AddField(
            model_name='customerpreference',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_preferences', to='geo.city'),
        ),
    ]
