# Generated by Django 5.2.4 on 2026-08-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_city_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('item', 'Item'), ('deal', 'Deal')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='restaurants.deal')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='restaurants.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='saved_user_created_idx'), models.Index(fields=['user', 'target_type'], name='saved_user_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', True), ('menu_item__isnull', False)), models.Q(('deal__isnull', False), ('menu_item__isnull', True)), _connector='OR'), name='saved_exactly_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', False), ('target_type', 'item')), models.Q(('deal__isnull', False), ('target_type', 'deal')), _connector='OR'), name='saved_type_matches_fk'), models.UniqueConstraint(condition=models.Q(('menu_item__isnull', False)), fields=('user', 'menu_item'), name='unique_saved_user_item'), models.UniqueConstraint(condition=models.Q(('deal__isnull', False)), fields=('user', 'deal'), name='unique_saved_user_deal')],
            },
        ),
    ]
