# Generated by Django 5.2.4 on 2026-08-18 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_saved_item'),
        ('restaurants', '0006_freeform_price_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_type', models.CharField(choices=[('item', 'Item'), ('deal', 'Deal')], max_length=10)),
                ('reason', models.CharField(choices=[('misleading_price', 'Misleading price'), ('photo_mismatch', 'Photo not the real dish'), ('unavailable', 'Unavailable'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='restaurants.deal')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='restaurants.menuitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='report_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', True), ('menu_item__isnull', False)), models.Q(('deal__isnull', False), ('menu_item__isnull', True)), _connector='OR'), name='report_exactly_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', False), ('target_type', 'item')), models.Q(('deal__isnull', False), ('target_type', 'deal')), _connector='OR'), name='report_type_matches_fk'), models.UniqueConstraint(condition=models.Q(('menu_item__isnull', False)), fields=('created_by', 'menu_item'), name='unique_report_user_item'), models.UniqueConstraint(condition=models.Q(('deal__isnull', False)), fields=('created_by', 'deal'), name='unique_report_user_deal')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='rating_stars_1_to_5'), models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_rating_user_restaurant')],
            },
        ),
    ]
