# Generated by Django 5.0.1 on 2026-08-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0004_deal_is_promoted_deal_promoted_ends_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("live", "Live"),
                            ("changes", "Changes"),
                            ("ended", "Ended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_start", models.DateTimeField()),
                ("requested_end", models.DateTimeField()),
                ("admin_note", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("goes_live_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to="restaurants.deal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to="restaurants.restaurant",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_promotion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("impression_count", models.PositiveIntegerField(default=0)),
                ("detail_views", models.PositiveIntegerField(default=0)),
                ("call_clicks", models.PositiveIntegerField(default=0)),
                ("whatsapp_clicks", models.PositiveIntegerField(default=0)),
                ("direction_clicks", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("save_count", models.PositiveIntegerField(default=0)),
                ("follow_count", models.PositiveIntegerField(default=0)),
                ("engagement_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_campaigns",
                        to="restaurants.deal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_campaigns",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "promotion_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="promotions.promotionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="promotionrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deal__isnull", True), ("menu_item__isnull", False)),
                    models.Q(("deal__isnull", False), ("menu_item__isnull", True)),
                    _connector="OR",
                ),
                name="promo_req_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="featuredcampaign",
            index=models.Index(
                fields=["started_at", "ends_at"], name="feat_campaign_window_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="featuredcampaign",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deal__isnull", True), ("menu_item__isnull", False)),
                    models.Q(("deal__isnull", False), ("menu_item__isnull", True)),
                    _connector="OR",
                ),
                name="feat_campaign_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="featuredcampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("menu_item__isnull", False)),
                fields=("menu_item", "started_at"),
                name="unique_feat_campaign_item_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="featuredcampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deal__isnull", False)),
                fields=("deal", "started_at"),
                name="unique_feat_campaign_deal_start",
            ),
        ),
    ]
