# Generated by Django 5.0.1 on 2026-08-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0004_deal_is_promoted_deal_promoted_ends_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impression_count", models.PositiveIntegerField(default=0)),
                ("detail_views", models.PositiveIntegerField(default=0)),
                ("call_clicks", models.PositiveIntegerField(default=0)),
                ("whatsapp_clicks", models.PositiveIntegerField(default=0)),
                ("direction_clicks", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("save_count", models.PositiveIntegerField(default=0)),
                ("follow_count", models.PositiveIntegerField(default=0)),
                ("engagement_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="restaurants.deal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = anonymous aggregate used for ranking.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_resource",
                "indexes": [
                    models.Index(
                        fields=["menu_item", "user"], name="analytics_item_user_idx"
                    ),
                    models.Index(
                        fields=["deal", "user"], name="analytics_deal_user_idx"
                    ),
                    models.Index(
                        fields=["-engagement_score"], name="analytics_score_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resourceanalytics",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deal__isnull", True), ("menu_item__isnull", False)),
                    models.Q(("deal__isnull", False), ("menu_item__isnull", True)),
                    _connector="OR",
                ),
                name="analytics_exactly_one_resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceanalytics",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("menu_item__isnull", False), ("user__isnull", False)
                ),
                fields=("menu_item", "user"),
                name="unique_analytics_item_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceanalytics",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deal__isnull", False), ("user__isnull", False)),
                fields=("deal", "user"),
                name="unique_analytics_deal_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceanalytics",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("menu_item__isnull", False), ("user__isnull", True)
                ),
                fields=("menu_item",),
                name="unique_analytics_anon_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceanalytics",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deal__isnull", False), ("user__isnull", True)),
                fields=("deal",),
                name="unique_analytics_anon_deal",
            ),
        ),
    ]
