# Generated by Django 5.0.1 on 2026-08-08 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0004_deal_is_promoted_deal_promoted_ends_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("serve_count", models.PositiveIntegerField(default=0)),
                ("watched_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("skip", "Skip"),
                            ("watch", "Watch"),
                            ("complete", "Complete"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("first_served_at", models.DateTimeField(auto_now_add=True)),
                ("last_served_at", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_impressions",
                        to="restaurants.deal",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_impressions",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_impressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedViewerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("promoted_rotate_offset", models.PositiveIntegerField(default=0)),
                ("organic_item_rotate_offset", models.PositiveIntegerField(default=0)),
                ("organic_deal_rotate_offset", models.PositiveIntegerField(default=0)),
                ("last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_viewer_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="feedimpression",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ip_hash__isnull", True), ("user__isnull", False)),
                    models.Q(("ip_hash__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="feed_impr_user_xor_ip",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedimpression",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("deal__isnull", True), ("menu_item__isnull", False)),
                    models.Q(("deal__isnull", False), ("menu_item__isnull", True)),
                    _connector="OR",
                ),
                name="feed_impr_exactly_one_resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedimpression",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("menu_item__isnull", False), ("user__isnull", False)
                ),
                fields=("user", "menu_item"),
                name="unique_feed_impr_user_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedimpression",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deal__isnull", False), ("user__isnull", False)),
                fields=("user", "deal"),
                name="unique_feed_impr_user_deal",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedimpression",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("ip_hash__isnull", False), ("menu_item__isnull", False)
                ),
                fields=("ip_hash", "menu_item"),
                name="unique_feed_impr_ip_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedimpression",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deal__isnull", False), ("ip_hash__isnull", False)),
                fields=("ip_hash", "deal"),
                name="unique_feed_impr_ip_deal",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedviewerstate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("ip_hash__isnull", True), ("user__isnull", False)),
                    models.Q(("ip_hash__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="feed_viewer_user_xor_ip",
            ),
        ),
    ]
